### ISSUE TITLE
Not working out of the box

### ISSUE THREAD

**Issue by themadsens** [Billiam/promise.lua#1]
It seems you have to supply Promise.async or somesuch to make it take off on *:resolve()

**Comment by Billiam** [comment]
I'm not sure I follow. Can you provide an example?

**Comment by themadsens** [comment]
The promise never ran the code setup with :next() on resolve.

I traced it to line 37 where the whole thing is parked on 'queue' and forgotten ..

```
local do_async = function(callback)
  if Promise.async then
    Promise.async(callback)
  else
    table.insert(queue, callback)              // <---  Line 37
  end
end
```

**Comment by Billiam** [comment]
Got it. That's by design, per the a+ promises spec. Promises must always be asynchronous.

Depending on your needs (and environment), you can either periodically call Promise.update(), or you can define a Promise.async method which will schedule a callback.  See here: https://github.com/Billiam/promise.lua/blob/master/README.md#installation

Hope that helps!

**Comment by themadsens** [comment]
Ah. I see. Wasn't aware that Q set this up in node "behind the scenes".

Releveant A+ paragraph: >>> onFulfilled or onRejected must not be called until the execution context stack contains only platform code. [3.1]. <<<

**Comment by themadsens** [comment]
The promise never ran the code setup with :next() on resolve.

I traced it to line 37 where the whole thing is parked on 'queue' and
forgotten ..
Switching to another promise library solved my problem :-)

local do_async = function(callback)
if Promise.async then
Promise.async(callback)
else
table.insert(queue, callback)
end
end
